version: '3.8'

services:
  app:
    image: wiraphong2003/web_hook_line:latest
    # ถ้าต้องการ build จาก local แทน สามารถใช้:
    # build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SERVER=${DB_SERVER}
    restart: always
    networks:
      - line-webhook-network

networks:
  line-webhook-network:
    driver: bridge